[package]
name = "rxla-pjrt"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Safe Rust bindings and dynamic plugin loading for the PJRT C API"

[dependencies]
half = { workspace = true }
libloading = "0.8"
smallvec = "=2.0.0-alpha.13"
snafu = "0.9.2"
tracing = { version = "0.1.44", default-features = false, features = ["std"] }
